"""initial_schema

Revision ID: 7cc25f9ef2bf
Revises: 
Create Date: 2026-06-07 20:29:03.111432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7cc25f9ef2bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'done', 'failed', name='videostatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('video_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('models_requested', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('video_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('incident_type', sa.Enum('FIRE', 'SMOKE', 'ACCIDENT', 'VIOLENCE', 'NONE', name='incidenttype'), nullable=False),
    sa.Column('detected', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_timestamps', sa.JSON(), nullable=False),
    sa.Column('frame_screenshot_url', sa.Text(), nullable=True),
    sa.Column('report_url', sa.Text(), nullable=True),
    sa.Column('incident_summary', sa.Text(), nullable=True),
    sa.Column('alert_status', sa.Enum('pending', 'sent', 'failed', 'retrying', 'skipped', name='alertstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('authorities_notified', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('n8n_execution_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'sent', 'failed', 'retrying', 'skipped', name='alertstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_logs')
    op.drop_table('incidents')
    op.drop_table('processing_jobs')
    op.drop_table('videos')
    # ### end Alembic commands ###
